Update Build-immortalWrt.yml

diff --git a/.github/workflows/Build-immortalWrt.yml b/.github/workflows/Build-immortalWrt.yml
--- a/.github/workflows/Build-immortalWrt.yml
+++ b/.github/workflows/Build-immortalWrt.yml
@@ -81,6 +81,29 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
         
+      - name: Cleanup
+        run: |
+          echo "Fetching list of cache key"
+          cacheKeysForPR=$(gh cache list --ref $BRANCH --limit 100 --json id --jq '.[].id')
+
+          ## Setting this to not fail the workflow while deleting cache keys.
+          set +e
+          echo "Deleting caches..."
+          for cacheKey in $cacheKeysForPR
+          do
+              gh cache delete $cacheKey
+          done
+          echo "Done"
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          GH_REPO: ${{ github.repository }}
+          BRANCH: refs/pull/${{ github.event.pull_request.number }}/merge
+      
+      - name: exit
+        id: building
+        run: |
+          exit 1
+              
       - name: Enable Cache
         uses: actions/cache@main
         with:
